n=int(input())
for i in range(n):
    ch=0
    print("------MENU-----")
    print("1. Square")
    print("2. Rectangle")
    print("3. Rhombus")
    print("4. Parallelogram")
    print("5. Circle")
    print("6. Cube")
    print("7. Cuboid")
    print("8. Right circular cone")
    print("9. Hemisphere")
    print("10. Sphere")
    print("11. Solid cylinder")
    print("12. Hollow cylinder")
    print("13. Exit")
    ch=int(input())
    if ch==1:
        s=float(input("Enter side of square: "))
        print("Perimeter of square is:",4*s)
        print("Area of square is:",s*s)
    if ch==2:
        l=float(input("Enter length of rectangle: "))
        b=float(input("Enter breadth of rectangle: "))
        print("Perimeter of rectangle is:",2*(l+b))
        print("Area of rectangle is:",l*b)
    if ch==3:
        a=float(input("Enter side of rhombus: "))
        d1=float(input("Enter diagonal 1 of rhombus: "))
        d2=float(input("Enter diagonal 2 of rhombus: "))
        print("Perimeter of rhombus is:",4*a)
        print("Area of rhombus is:",0.5*d1*d2)
    if ch==4:
        l=float(input("Enter length of Parallelogram: "))
        b=float(input("Enter breadth of Parallelogram: "))
        h=float(input("Enter height of Parallelogram: "))
        print("Perimeter of Parallelogram is:",2*(a+b))
        print("Area of Parallelogram is:",b*h)
    if ch==5:
        r=float(input("Enter radius of circle: "))
        print("Circumference of circle is:",2*3.14*r)
        print("Area of circle is:",3.14*(r*r))
    if ch==6:
        s=float(input("Enter side of cube: "))
        print("CSA of cube is:",4*s*s)
        print("TSA of cube is:",6*s*s)
        print("Volume of cube is:",s*s*s)
    if ch==7:
        l=float(input("Enter length of cuboid: "))
        b=float(input("Enter breadth of cuboid: "))
        h=float(input("Enter height of cuboid: "))
        print("CSA of cuboid is:",2*h*(l+b))
        print("TSA of cuboid is:",2*(l*h+b*h+h*l))
        print("Volume of cuboid is:",l*b*h)
    if ch==8:
        l=float(input("Enter slant height of cone: "))
        r=float(input("Enter radius of cone: "))
        h=float(input("Enter height of cone: "))
        print("CSA of cone is:", 3.14*r*l)
        print("TSA of cone is:",3.14*r*(r+l))
        print("Volume of cone is:",(3.14*r*r*h)/3)
    if ch==9:
        r=float(input("Enter radius of hemisphere: "))
        print("CSA of hemisphere is:", 2*3.14*r*r)
        print("TSA of hemisphere is:",3*3.14*r*r)
        print("Volume of hemisphere is:",(2*3.14*(r**3))/3)
    if ch==10:
        r=float(input("Enter radius of sphere: "))
        print("CSA of sphere is:",4*3.14*r*r)
        print("TSA of sphere is:",4*3.14*r*r)
        print("Volume of sphere is:",(4*3.14*(r**3))/3)
    if ch==11:
        r=float(input("Enter radius of Solid cylinder: "))
        h=float(input("Enter height of Solid cylinder: "))
        print("CSA of Solid cylinder is:",2*3.14*r*h)
        print("TSA of Solid cylinder is:",2*3.14*r*(r+h))
        print("Volume of Solid cylinder is:",3.14*r*r*h)
    if ch==12:
        R=float(input("Enter outer radius of Hollow cylinder: "))
        r=float(input("Enter inner radius of Hollow cylinder: "))
        h=float(input("Enter height of Hollow cylinder: "))
        print("CSA of Hollow cylinder is:",2*3.14*h*(r+R))
        print("TSA of Hollow cylinder is:",(2*3.14*h*(r+R))+ (2*3.14*((R**2)-(r**2))))
        print("Volume of Hollow cylinder is:",3.14*h*((R**2)-(r**2))) 
    
